#!/usr/bin/python3

import os,sys

if len(sys.argv) != 3:
    print ("usage: proj_seach has|hasnot search_term")
    exit (1)

# operation
operation=sys.argv[1]

if operation != "has" and operation != "hasnot":
    print ("ERROR:",operation,"is not a valid operation.")
    exit (1)

# search string
search_str=sys.argv[2]
 
# The top argument for walk
topdir = '.'

# The extension to search for
exten = '.proj'

for dirpath, dirnames, files in os.walk(topdir):
    for name in files:
        if name.lower().endswith(exten):
            foundLine="false"

            fname = os.path.join(dirpath, name)
            fo = open(fname)
            line = fo.readline()

            while line != '':
                line = line.strip()
                index = line.find(search_str)
                if (index != -1):
                    foundLine="true"
                    if (operation == "has"):
                        print(fname, ": ", line)
                line = fo.readline()
            if (operation == "hasnot" and foundLine == "false"):
                print(fname, ": ", line)
            fo.close()

